import React from 'react';

export default function DocsPage() {
  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-20">
      <div className="mb-12">
        <h1 className="text-4xl font-bold text-[var(--color-text)] mb-4 tracking-tight">Caliber Documentation</h1>
        <p className="text-lg text-[var(--color-text-muted)]">
          The comprehensive A-Z guide for configuring, monitoring, and evaluating your AI agents with Caliber.
        </p>
      </div>

      <div className="space-y-12">
        <section className="glass-card p-8">
          <h2 className="text-2xl font-semibold text-[var(--color-text)] mb-4">1. What does Caliber do?</h2>
          <div className="prose prose-sm sm:prose-base dark:prose-invert text-[var(--color-text-muted)]">
            <p>
              Caliber is a specialized AI evaluation and monitoring platform. As Large Language Models (LLMs) and autonomous agents become deeply integrated into software systems, tracking their performance natively becomes difficult. 
            </p>
            <p>
              Caliber provides a centralized dashboard to observe AI payload latencies, track accuracy scores, flag toxic responses, and strictly monitor regressions involving Personally Identifiable Information (PII). It gives engineers the analytic power to know *exactly* how their agents behave over time.
            </p>
          </div>
        </section>

        <section className="glass-card p-8">
          <h2 className="text-2xl font-semibold text-[var(--color-text)] mb-4">2. Core Concepts</h2>
          <div className="grid md:grid-cols-2 gap-6 text-[var(--color-text-muted)]">
            <div>
              <h3 className="font-semibold text-[var(--color-text)] mb-2">Evaluations (Evals)</h3>
              <p className="text-sm">An &quot;Eval&quot; is a single recorded interaction between your system and an AI model. It logs the prompt, the model&apos;s response, execution time, and qualitative metrics generated by our analyzers.</p>
            </div>
            <div>
              <h3 className="font-semibold text-[var(--color-text)] mb-2">Metrics Engine</h3>
              <p className="text-sm">We automatically score each Eval across multiple dimensions: <strong>Accuracy</strong> (factual correctness), <strong>Latency</strong> (speed), <strong>Safety</strong> (toxicity checks), and <strong>PII Isolation</strong> (ensuring no protected user data is leaked).</p>
            </div>
          </div>
        </section>

        <section className="glass-card p-8">
          <h2 className="text-2xl font-semibold text-[var(--color-text)] mb-4">3. Platform Features </h2>
          <div className="space-y-6 text-[var(--color-text-muted)]">
            <div>
              <h3 className="text-lg font-semibold text-[var(--color-text)]">Configuration & Setup</h3>
              <p className="text-sm mt-1">Navigate to the <strong>Config</strong> page to establish your environment variables, target models, and safety thresholds. This tells Caliber how strictly to grade your specific application&apos;s outputs.</p>
            </div>
            <div className="h-px bg-[var(--surface-border)] w-full" />
            <div>
              <h3 className="text-lg font-semibold text-[var(--color-text)]">Data Portability (CSV/JSON Export)</h3>
              <p className="text-sm mt-1">Found an anomaly? In the <strong>Evaluations</strong> table, you can export your filtered view to CSV or JSON formats. This portability allows your data science teams to perform deeper offline analysis or build custom historical reports.</p>
            </div>
            <div className="h-px bg-[var(--surface-border)] w-full" />
            <div>
              <h3 className="text-lg font-semibold text-[var(--color-text)]">Granular Search & Filtering</h3>
              <p className="text-sm mt-1">The Evaluations ledger features robust multi-parameter filtering. Drill down by date ranges, score thresholds, or specifically isolate categories to pinpoint exactly where models are failing.</p>
            </div>
            <div className="h-px bg-[var(--surface-border)] w-full" />
            <div>
              <h3 className="text-lg font-semibold text-[var(--color-text)]">Role Based UI (Admin vs Viewer)</h3>
              <p className="text-sm mt-1">Caliber enforces strict visual and functional boundaries depending on the user&apos;s role. <strong>Admins</strong> have full write-access to system configs and manual evaluation creation. <strong>Viewers</strong> are bound to read-only states, preventing accidental or malicious configuration overrides.</p>
            </div>
            <div className="h-px bg-[var(--surface-border)] w-full" />
            <div>
              <h3 className="text-lg font-semibold text-[var(--color-text)]">Trend Analysis Dashboard</h3>
              <p className="text-sm mt-1">The <strong>Dashboard</strong> aggregates metric streams into rich, chronological charts. Visualize latency spikes over a 30-day window or track the success rate of your PII-redaction models in a clean, visual format.</p>
            </div>
          </div>
        </section>

        <section className="glass-card p-8">
          <h2 className="text-2xl font-semibold text-[var(--color-text)] mb-4">4. How to Ingest Data</h2>
          <div className="prose prose-sm sm:prose-base dark:prose-invert text-[var(--color-text-muted)]">
            <p>
              To push data into Caliber, direct your backend services to hit our ingestion endpoint upon completing an AI transaction:
            </p>
            <pre className="bg-[var(--color-surface-elevated)] p-4 rounded-xl border border-[var(--surface-border)] overflow-x-auto mt-4">
              <code className="text-sm font-mono text-[var(--color-text)]">
{`// POST /api/evals/ingest
fetch('https://caliber-ai.vercel.app/api/evals/ingest', {
  method: 'POST',
  headers: { 'Content-Type': 'application/json' },
  body: JSON.stringify({
    prompt: "Summarize the user profile.",
    response: "The user is John Doe, residing in NYC.",
    latency_ms: 850,
    category: "Summarization",
    metadata: { model: "gpt-4-turbo" }
  })
});`}
              </code>
            </pre>
            <p className="mt-4">
              The ingestion engine will automatically calculate PII risk factors, assign accuracy benchmarks based on your configuration parameters, and surface the data directly to your Dashboard in real-time.
            </p>
          </div>
        </section>
      </div>
    </div>
  );
}